// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OiA.Repository;
using System;

namespace OiA.Migrations
{
    [DbContext(typeof(OiAContextcs))]
    [Migration("20180425163700_UpdateFileDetailTableStructure")]
    partial class UpdateFileDetailTableStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OiA.Repository.FileDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Extension")
                        .IsRequired();

                    b.Property<DateTime>("FileCreationTimeUtc");

                    b.Property<DateTime>("FileLastAccessTimeUtc");

                    b.Property<DateTime>("FileLastWriteTimeUtc");

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<long>("Length");

                    b.Property<string>("Md5Hash")
                        .HasMaxLength(32);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Md5Hash")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("FileSystem");
                });

            modelBuilder.Entity("OiA.Repository.PendingFile", b =>
                {
                    b.Property<string>("FileFullName")
                        .ValueGeneratedOnAdd();

                    b.HasKey("FileFullName");

                    b.ToTable("PendingFile");
                });
#pragma warning restore 612, 618
        }
    }
}
